### ISSUE TITLE
not all chants showing up

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/cantus#664] opened 2023-01-16 18:35 UTC
On some (?) manuscripts, there seems to be a limit on how many chants show up in the side bar. 
For example, on CH-FCo 2, folio 4r lists 4 chants, when there are records for 8 on the Cantus database. 
https://cantus.simssa.ca/manuscript/75/?folio%5B0%5D=004r&pageAlias=Folio%20004r
The same is true for most of the folios in this MS--about three or four chants will show up, but there are more on the page. 

And it's not just this MS! The same problem happens on Einsie: https://cantus.simssa.ca/manuscript/74/?folio%5B0%5D=001v&pageAlias=Folio%20001v
as well as:
D-Mbs 4303: https://cantus.simssa.ca/manuscript/91/?folio%5B0%5D=010v&pageAlias=Folio%20010v
D-Mbs 4306: https://cantus.simssa.ca/manuscript/94/?folio%5B0%5D=002v&pageAlias=Folio%20002v
F-Pnm Lat 15181: https://cantus.simssa.ca/manuscript/139/?folio%5B0%5D=016v&pageAlias=Folio%20016v
F-Pnm 12044: https://cantus.simssa.ca/manuscript/136/?folio%5B0%5D=001r&pageAlias=Folio%20001r
CH-StGallen 388: https://cantus.simssa.ca/manuscript/77/?folio%5B0%5D=023&pageAlias=Folio%20023
CH-StGallen 390 https://cantus.simssa.ca/manuscript/79/?folio%5B0%5D=009&pageAlias=Folio%20009
CH-StGallen 391 https://cantus.simssa.ca/manuscript/78/?folio%5B0%5D=007&pageAlias=Folio%20007
CH-P 18: https://cantus.simssa.ca/manuscript/76/?folio%5B0%5D=013&pageAlias=Folio%20013

and both versions of Salzinnes (interestingly, showing different numbers of chants on the same page)
https://cantus.simssa.ca/manuscript/209/?folio%5B0%5D=007v&pageAlias=Folio%20007v
https://cantus.simssa.ca/manuscript/25/?folio%5B0%5D=007v&pageAlias=Folio%20007v

I can't tell what determines how many chants show up--sometimes it seems like it's consistently the first three chants of every page, but sometimes it seems like what shows up or not is variable from one folio to another. 

I think it is also an issue for F-TOm 149 and D-Ka Aug LX but there are some other mapping issues as well:
https://cantus.simssa.ca/manuscript/146/?folio%5B0%5D=004r&folio%5B1%5D=004v&pageAlias=Folio%20004r%2C%20004v
https://cantus.simssa.ca/manuscript/87/?folio%5B0%5D=006v&pageAlias=Folio%20006v

**Comment by dchiller** [comment] 2023-01-20 22:51
Not great! An initial investigation...

Taking your first example, I had a look at the database, and folio "004r" of CH-Fco 2 has 8 chants in there:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/11023634/213818387-76bff7be-8cf1-4ad2-bf89-469b35957ed2.png">

This is the number we expect, as you say. I compared the list in the CU db and in [CantusDB ](https://cantus.uwaterloo.ca/chants?source=123672&folio=004r) and they match. 

However, the search query that runs behind the scenes to pull up the chants in CU when you scroll to the folio only turns up the 4 that you see: 

<img width="578" alt="image" src="https://user-images.githubusercontent.com/11023634/213818688-edfcd54f-9e0c-4e09-9da3-feee59bd4d87.png">

So, something is happening between the DB and the search results. 

Need to stop for the moment, but there's even more weirdness when we try to search for the chants on this page in the CU search bar.

**Comment by dchiller** [comment] 2023-01-21 21:51
I can reproduce the odd search behavior locally, although the specific errors are slightly different than the ones above. All the expected folios show up in the folio detail panel...

If we directly query the solr server, here's what I get locally:
<img width="949" alt="image" src="https://user-images.githubusercontent.com/11023634/213888127-35a15dc8-a656-4b6c-be02-88a626956a82.png">

and here's what I get on the production server:
<img width="958" alt="image" src="https://user-images.githubusercontent.com/11023634/213888243-623a55f9-3f27-4106-8c00-c57848bf2b2f.png">

So for some reason, on the production server we have the data in the database but it is not in the solr index, while locally, we have the data in the database and the solr index. 

This also matches an issue we had where the image_uris for various folios on production were in the database but not in the solr index. So for some reason on production, we are finding multiple gaps in the solr index.

A complete rebuilding of the solr index from the database should solve this immediate problem, but it is still concerning why so many gaps exist in the first place. Was there some kind of solr error when these were first loaded in the database, and we are now catching the various fallout from this error? Since I've been unable to replicate locally, this seems to be the case. 

I'll see what happens with a solr index rebuild, and then it's probably worth keeping an eye out with what happens on future imports -- was this a fluke, or are there going to be issues with solr whenever we add a new manuscript?

**Comment by dchiller** [comment] 2023-01-22 13:46
Attempts to reindex are running into issues:

1. After re-indexing, all chants now appear in double.
2. Reindexing leads to a solr out of memory error and therefore was not fully completed -- maybe this is what is causing them to show up doubly?

**Comment by dchiller** [comment] 2023-01-23 02:12
Reindexing again:

1. Chants and manuscripts are doubly added to the index, while folios are only added singly. 
2. After repeated reindexing, some lead to an out of memory error and some attempts do not. No clear reason for either of these.

**Comment by dchiller** [comment] 2023-01-23 02:19
Added issues #668 and #669 to solve this.

**Comment by dchiller** [comment] 2023-05-08 16:31
This issue (ie. chants not showing up on the production site) is solved. The issues branching from this still need to be resolved, but closing this as those are separately documented.

**Closed by dchiller** 2023-05-08 16:31 UTC
