### ISSUE TITLE
Fixed header in the search results scroll

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#260] opened 2016-05-18 23:29 UTC
It would be good to have a fixed header in the search results table ('Folio,' 'Incipit', etc.) so that the contents of the table cell are always labelled. Right now when we scroll we lose what bit of information 'U' or '4' represents.

**Comment by jeromepl** [comment] 2016-05-20 15:52
Duplicate of #146

**Closed by jeromepl** 2016-05-20 15:52 UTC
Labels: Enhancement, Medium Priority, Public Website

**Comment by ahankinson** [comment] 2016-05-20 18:39
My bad! Sorry.
