### ISSUE TITLE
Page gets 'stuck' in Chrome

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#206] opened 2015-06-26 21:51 UTC
Reproduce: In Chrome, do an OMR search. Find a result. Double-click to zoom in. 

What happens: You can't move the page horizontally.

This seems to be OK in Safari. Haven't checked Firefox.

**Comment by wabain** [comment] 2015-06-26 21:57
Can't reproduce this; can you verify that it happens consistently? It happened once before (when I was showing Utrecht 406) that I zoomed into the page and then couldn't move around. I was never able to reproduce that either.

**Comment by ahankinson** [comment] 2015-06-26 22:12
It's pretty consistent for me. Maybe try with a trackpad?

**Comment by ahankinson** [comment] 2015-06-26 22:14
It seems the OMR search bit is crucial. I can zoom in and out and move around with out it.

Reload page.
Go to OMR search
Search pitches 'edcdee'
Click the + button

**Comment by wabain** [comment] 2015-06-29 14:22
I can reproduce it now. There's some intermittence to it (my off the cuff guess is that it's something about the order requests get resolved in) but now I can get it to happen when I just go to the page and zoom in.

**Comment by wabain** [comment] 2015-06-29 15:16
So this seems to be an actual Chromium bug. The width of the `diva-inner` element is being set correctly, but the browser *doesn't actually resize the element*. Here's a screenshot: the width value visible under `element.style` in the dev console is `2261px`, but the value in the box model view on the right, which is what's actually being displayed, is 622. Toggle the width value of and on again in the dev console and the size corrects itself. It should be easy enough to add a patch to force the width to take, but this is still kind of unsettling.

![screen shot 2015-06-29 at 11 06 51 am](https://cloud.githubusercontent.com/assets/7651435/8411026/b2c0bd5c-1e4f-11e5-9bee-fba8aa86594d.png)

**Comment by wabain** [comment] 2015-06-29 18:15
I have a not very good workaround that seems to be reliable, but I still have no idea what's really going on.

**Comment by wabain** [comment] 2015-07-29 15:05
Closing this because the workaround seems to be doing its job and I don't expect a better fix to come around.

**Closed by wabain** 2015-07-29 15:05 UTC
Labels: Bug, High Priority, Public Website
